fix: remove type decorations from stylesheets
zardoy/vscode-experiments pull request #7
Opened 2022-06-14 22:38 UTC by ILScc

2022-06-15 11:39 UTC, zardoy commented on src/features/typeDecorations.ts
> +        console.log('stylesLangs.includes(languageId)', stylesLangs.has(languageId))
Unnecessary logging

2022-06-15 11:58 UTC, zardoy commented
Are you sure we should disable it in styles? It still can give useful piece of information such as syntax hint. 
![image](https://user-images.githubusercontent.com/46503702/173821373-d88d279e-4b28-45e0-a0c9-3ffbc3c3368b.png)

The problem here is that we're printing raw markdown instead of *rendered* version: https://github.com/microsoft/vscode/issues/147530 (e.g. we shouldn't use [`.value`](https://github.com/zardoy/vscode-experiments/blob/2ce643202ae7ac688ad9013c668a5e278efdd7f8/src/features/typeDecorations.ts#L58))

2022-06-16 15:36 UTC, ILScc commented
Removing `.value` doesn't help as `content` in this case evaluates in `l {}` 
![image](https://user-images.githubusercontent.com/74474615/174105831-88f87572-8ec7-498b-8446-2a49711e3f49.png)

> Are you sure we should disable it in styles? It still can give useful piece of information such as syntax hint. ![image](https://user-images.githubusercontent.com/46503702/173821373-d88d279e-4b28-45e0-a0c9-3ffbc3c3368b.png)
> 
> The problem here is that we're printing raw markdown instead of _rendered_ version: [microsoft/vscode#147530](https://github.com/microsoft/vscode/issues/147530) (e.g. we shouldn't use [`.value`](https://github.com/zardoy/vscode-experiments/blob/2ce643202ae7ac688ad9013c668a5e278efdd7f8/src/features/typeDecorations.ts#L58))

`vscode.MarkdownString` and `vscode.MarkedString` escape their values under the hood, so I had to use lodash's `unescape` (I didn't find equivalent in `rambda`) method in order to produce human-readable string

2022-06-16 15:38 UTC, zardoy commented
I'll look into this in a few hours.

@ILScc by the way how tailwind in css is going?

2022-06-26 20:43 UTC, zardoy commented
My thoughts on this for now:

We should either disable them in style blocks completely out of the box or implement the setting with the value disabled by default. You can do this on your own, I won't care. In case of impl setting, you can leave lodash method..

@ILScc just like with renameVariableParts you need to pick latest commits from main to fix CI (or rebase; you don't need to supress warning as they don't affect CI).

2022-06-26 20:45 UTC, zardoy requested changes

2022-06-26 20:45 UTC, zardoy commented on src/features/typeDecorations.ts
> +            const typeMatch = (await checkIfInStyles(document, pos)) ? /Syntax: (.*)/.exec(hoverString) : /: (.+)/.exec(hoverString)
@ILScc why did you supress `no-await-in-loop`? You actually could actually done this check before loop. This is not optimal.

2022-06-29 11:29 UTC, ILScc commented on src/features/typeDecorations.ts
> +            typeString = unescape(typeMatch[1]!).replaceAll('\\', '')
Added this to remove annoying `\` in output 
![image](https://user-images.githubusercontent.com/74474615/176426355-9ff4c1fd-ef2b-452a-a973-65f6fa2e3705.png)

2022-06-29 11:34 UTC, ILScc commented on src/features/typeDecorations.ts
> +        if (!getExtensionSetting('typeDecorationsInStyles.enable')) return false
I understand the solution insn't efficient, but right now I just wanted it to work :)

2022-06-29 11:39 UTC, zardoy commented
Wait a second, I'll check it

2022-06-29 11:51 UTC, zardoy commented
@ILScc can you please check 2 new commits and merge if the code is fine. I already checked the behavior. Some notes:

- From [Contribution Point guides](https://code.visualstudio.com/api/references/contribution-points) we need to follow the structure of settings:
`category.someThing` so I renamed it to `typeDecorations.enableInStyles` to match category.
- I already [stated above](https://github.com/zardoy/vscode-experiments/pull/7#issuecomment-1156380997) that we need to transform MarkDown syntax text into "rendered text". unescape had nothing in common with MarkDown so I replaced it with appropriate lib (you can check lib description to better understand the intention)

2022-06-29 12:26 UTC, merged